### ISSUE TITLE
gulp-release is not a real module

### ISSUE THREAD

**Issue by jquense** [Pestov/essential-gulp-plugins#3]
The repo listed here exports a noop function, someone is just squatting on the name. Maybe a different thing was meant?

**Comment by Pestov** [comment]
Sorry for my inattention, you are right 74c44c8. I missed it, because firstly I gathered [plugins for Grunt](https://github.com/Pestov/essential-grunt-plugins). If you need a task for versions, you can use grunt-release module with gulp-grunt for Gulp.
